# pidfile = 'app01.pid'
# worker_tmp_dir = '/dev/shm'
# worker_class = 'gthread'
# workers = 2
# worker_connections = 1000
# timeout = 30
# keepalive = 2
# threads = 4
# proc_name = 'app01'
# bind = '0.0.0.0:8080'
# backlog = 2048
# accesslog = '-'
# errorlog = '-'
# user = 'ubuntu'
# group = 'ubuntu'

# NUM_WORKERS=3
# TIMEOUT=3000
workers = 2
timeout = 3000